### PR TITLE
Add total pairs shit

### PR DESCRIPTION
**Pull request by jonahgeorge**
- Also splits all of the classes out into their own files
- Adds consistent ordering of pairs

### CODE REVIEW

**Comment by jonahgeorge** [comment]
@jordancrane If you have a working Hadoop instance, would you mind testing this just to make sure I didn't miss anything

**Comment by jordancrane** [comment]
@jonahgeorge Is maven referencing java 8 for your build? I'm not familiar with the tool, but it's throwing some errors for me when I try to build.

**Comment by jonahgeorge** [comment]
What sort of errors are you getting? Here's the version I'm currently running:

```
➜  ~ mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.4", arch: "x86_64", family: "mac"
```

**Comment by jordancrane** [comment]
So, I figured out compilation; you're referencing Java 1.8 for compilation, and I've been using Java 1.7. I installed java 1.8 and was able to compile. Now I can't run it though, I think because my hadoop install is using Java 1.7. It's throwing the following error: `Exception in thread "main" java.lang.UnsupportedClassVersionError: PurchaseNetwork : Unsupported major.minor version 52.0`. I'm currently trying to change the Java version being used by my hadoop to 1.8. I'll let you know if I figure it out.

**Comment by jordancrane** [comment]
How did you get your Hadoop instance running with Java 8? Installing it broke my instance, but then it resumed working when I uninstalled it. I think the moral of the story here is that the dev environment that I set up for this project sucks, but I don't want to break it at this point. I might try to run yours in a Docker container or something.

**Pull request merged**
